public class LibraAltaProveedorPayload 
{
	//public String numero_secuencia {set; get;}
	public String tipo_cambio {set; get;}
	public String codigo_empresa {set; get;}
	public String codigo_rapido {set; get;}
	public String nif {set; get;}
	public String nombre {set; get;}
	public String razon_social {set; get;}
	public String estado {set; get;}
	public String forma_pago {set; get;}
	public String divisa {set; get;}
	public String direccion {set; get;}
	public String localidad {set; get;}	
	public String codigo_postal {set; get;}
	public String provincia {set; get;}
	public String acreedor {set; get;}

	public LibraAltaProveedorPayload() 
	{
		
	}
}