public class OpportunityLineItemAWSPayload {
    public String img {set; get;}
    public String itm {set; get;}
    public String ean {set; get;}
    public String s_dsc {set; get;}
    public String itm_inf {set; get;}
    public String clr {set; get;}
    public String mtrial {set; get;}
    public String qty_crmr {set; get;}
    public String pack {set; get;}
    public String brnd {set; get;}
    public String moq {set; get;}
    public String fob {set; get;}
    public String cod_trff {set; get;}
    public String ctr20 {set; get;}
    public String ctr40 {set; get;}
    public String ctr40H {set; get;}
    public String ld_tm {set; get;}
    public String orig {set; get;}
    public String pt_lnd {set; get;}
    public String lrg {set; get;}
    public String wdth {set; get;}
    public String hght {set; get;}
    public String dmtr {set; get;}
    public String wght {set; get;}
    public String m3 {set; get;}
    public String xlrg {set; get;}
    public String xwdth {set; get;}
    public String xhght {set; get;}
    public String xwght {set; get;}
    public String xm3 {set; get;}
    public String vcst {set; get;}

    public OpportunityLineItemAWSPayload() {
    }

}